// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnwkzqfpswdzspxymqjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRud2t6cWZwc3dkenNweHltcWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDEzMDEsImV4cCI6MjA2OTkxNzMwMX0.27L07A-cpkr8WsyJnfgU7ZmInt7IVYt0iZhhs2zdles";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});